---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapscheduler
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: snapscheduler
  template:
    metadata:
      labels:
        name: snapscheduler
    spec:
      serviceAccountName: snapscheduler
      containers:
        - name: snapscheduler
          image: quay.io/backube/snapscheduler
          command:
            - snapscheduler
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "snapscheduler"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
