---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapscheduler
subjects:
- kind: ServiceAccount
  name: snapscheduler
  namespace: default
roleRef:
  kind: ClusterRole
  name: snapscheduler
  apiGroup: rbac.authorization.k8s.io
